Support parsing LLVM's new JSON streaming API
aras-p/ClangBuildAnalyzer pull request #25
Opened 2019-11-26 06:26 UTC by mendsley

LLVM added a JSON steaming output API in
https://reviews.llvm.org/D60804 and updated the TimeProfiler to use it:
https://github.com/llvm-mirror/llvm/blob/master/lib/Support/TimeProfiler.cpp#L164

This adds "prettifies" the JSON with whitespace and causes the "clang" metadata element to output as:
`    {
      "args": {
        "name": "clang"
      },
      "cat": "",
      "name": "process_name",
      "ph": "M",
      "pid": 1,
      "tid": 0,
      "ts": 0
    }`

This fails the quick check when scanning for files. The output from the
JSON formatter appears to be deterministic; this change adds the new
output format.

2019-11-26 06:28 UTC, mendsley commented on src/main.cpp
> +        std::string markerCheckStr = str;
Maybe overly paranoid to make a copy before modifying. Not sure if anything in the time profiler would ever output valid \r characters in JSON string literals.

2019-11-27 13:52 UTC, aras-p requested changes

2019-11-27 13:52 UTC, aras-p commented on src/main.cpp
>              return;
Hmm maybe this should get a bit relaxed treatment, like (typing out of the top of my head, might not compile):

```
const char* kClangMarker1 = "\"name\":\"clang\"";
const char* kClangMarker2 = "\"name\": \"clang\"";
const char* kProcessNameMarker1 = "\"name\":\"process_name\"";
const char* kProcessNameMarker2 = "\"name\": \"process_name\"";
if (strstr(str.c_str(), kClangMarker1) == NULL && strstr(str.c_str(), kClangMarker2) == NULL)
    return;
if (strstr(str.c_str(), kProcessNameMarker1) == NULL && strstr(str.c_str(), kProcessNameMarker2) == NULL)
    return;
```
and then there's no need to do newline conversion.

2020-02-26 06:54 UTC, aras-p commented
Hmm I'm testing with current LLVM/Clang 10.0 RC2 builds, and everything "just works" without this PR even. The JSON emitted by clang has the marker like `{"cat":"","pid":1,"tid":0,"ts":0,"ph":"M","name":"process_name","args":{"name":"clang-cl.exe"}}` and the current detection code handles it just fine.

I guess I'll close the PR; reopen it if you see different behavior.

2020-02-26 06:54 UTC, closed without merging